name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and restart service via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            set -e
            cd /home/url-shortener
            git pull origin master
            cd build
            cmake --build . -- -j$(nproc)
            sudo systemctl stop url-shortener.service || true
            sudo cp -rT /home/url-shortener/frontend /home/opt/frontend
            sudo cp bin/url_shortener /home/opt/
            sudo systemctl start url-shortener.service
